// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-games.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var GAMES = [
  { id: "sudoku", name: "Sudoku" },
  { id: "tetris", name: "Tetris" },
  { id: "quiz", name: "Quiz" },
  { id: "memory", name: "Memory" },
  { id: "math", name: "Math Game" },
  { id: "emoji", name: "Emoji Match" },
  { id: "wordscramble", name: "Word Scramble" },
  { id: "balloons", name: "Balloon Pop" },
  { id: "snake", name: "Snake" },
  { id: "typing", name: "Typing Game" },
  { id: "colormatch", name: "Color Match" },
  { id: "whackamole", name: "Whack-a-Mole" },
  { id: "simon", name: "Simon Says" }
];
var list_games_default = defineTool({
  name: "list_games",
  title: "List games",
  description: "List all games available in the Swipe & Play Arcade with their ids and display names.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(GAMES, null, 2) }],
    structuredContent: { games: GAMES }
  })
});

// src/lib/mcp/tools/get-leaderboard.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_leaderboard_default = defineTool2({
  name: "get_leaderboard",
  title: "Get leaderboard",
  description: "Get the top scores from the arcade. Optionally filter by a specific game id (e.g. 'snake', 'tetris').",
  inputSchema: {
    gameType: z.string().optional().describe("Optional game id to filter scores, e.g. 'snake'."),
    limit: z.number().int().min(1).max(50).optional().describe("How many top scores to return (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ gameType, limit }) => {
    const supabase = supabaseClient();
    let query = supabase.from("game_scores").select("id, user_id, game_type, score, created_at").order("score", { ascending: false }).limit(limit ?? 10);
    if (gameType) query = query.eq("game_type", gameType);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const userIds = [...new Set((data ?? []).map((r) => r.user_id))];
    const { data: profiles } = await supabase.from("profiles").select("id, username").in("id", userIds);
    const nameMap = new Map((profiles ?? []).map((p) => [p.id, p.username]));
    const rows = (data ?? []).map((r) => ({
      game_type: r.game_type,
      score: r.score,
      player: nameMap.get(r.user_id) ?? "Anonymous",
      created_at: r.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { leaderboard: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "swipe-and-play-arcade-mcp",
  title: "Swipe & Play Arcade MCP",
  version: "0.1.0",
  instructions: "Tools for the Swipe & Play Arcade. Use `list_games` to see the available retro games, and `get_leaderboard` to fetch top scores (optionally filtered by game id).",
  tools: [list_games_default, get_leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
