// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yovoezekqobmqtfjgfad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvdm9lemVrcW9ibXF0ZmpnZmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjU0MzUsImV4cCI6MjA2MjY0MTQzNX0.udkd9oUI-LOYVm04GXzrQsApUWYwjgg44KmC7s4vY2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);